language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "0.12"
  - "4"
  - "6"

script:
  - npm run build
  - npm run test
  - npm run cover

before_script:
  - mkdir -p dist reports

after_script:
  - npm install coveralls
  - cat ./reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
